---
branches:
  only:
    - master

env:
  global:
    # DOCKER_EMAIL
    - secure: "BwfzcUbryDey9M2dV4IQSknrrTUKwE5azbQljTJ6UXcoJ7pg7/a1TJwPZz5qUUkExakuLlvb73A1bzbROb5bs8E8PnvTb+4YM+s/6pPh0PetpoaE61yw5/BSItmdsN/Y6rSUUOyEViblch3ZZXuZJsn6bxoiSyFyXYsNWRvgF+R1uTFka6UZMHKrH0eP2jP+kjQ0lMcpUdeCrfqA1RZEyAI+OkR191X8p4iCeBAfKYA8PLEdW8cu0DsUSdHz4knQVLGj+T0p7qM2oM4OKdzjUeDe0fRW3CrN7YptvdjdCnqcTxwZ6PZSp32p0xXPWUdI/VOnucYdc+c9TV0HV0Trv7NV08FSBrWDzNQ3UGCNWuq1dmp+oZ9wjSk9nrQtdMKfE43NYS1oUPqqXo+HH+2Ly6Noot38R3+5I99RWeVjjHwROTIg/KRqzSvUKGzMNhOXhvgv9eMREOE498dBKw7kNi061vlN+gn8Sn1XHLFvs8jHYgNLUtISNG8z/DwKHvpnqyVvOgfnd1/3zK6BXrHfvUa3QFqbKYGWFSbwgvIz+0WpLzHa6igej06rkxce+DSxMp+esL6uo4T6Tr5nuzjLGbFR9OGjShxNGw+ZgGSZ4V1+QoDJnYVVKuULobFYJxx9FQRXeIRAX+BGRdmLd5fFgjgCp+8FvF/8B+UT/np7u2s="
    # DOCKER_USER
    - secure: "qLehesiaqWnQdjweZ8V42k7/biPYoDGV106dHBi195oVacfqtjTppMYpzndb6dgA6x2jgm4doV/Ksuc1NV9F4ehyo7lAQqP7DxGQ768QpvbSSDgyrUH09pm0RAFMlzwVfNu8zC+ZVZ+Do2bNNMhXbvA46dR48i8/Cvxyik6e81XZEyQ6HdwUu+luirhdLHi3PUsN+64oeIa57PC1XKmK+U8wgx2ZWUL6OHv8Eig1Yr3ZKLzbULu13NGyyjdQT5P783OEEVAp2YpRVMKFcEflz1aSksoLUWv2Zouj96kweY8xU492rhyGjdzfmcYKVqCd4+M4MIEOk8ZQfTDERN6ERUCLJx8s1YPlxbTZiCKLsAeISheQrRd7RYORzV9D5xn7Rl7+fgD50Tj0wuZoyQIdLhmOpfVuWB0fUH//tt6JqiWDKFb3XgVuzOcuROCGJksZ19TTJvP1eWIRxzI4fEsv4srP1Oo4XMk66e0apEmWJNH11751oIlMpOGg8L4AWBejmxoszJeFWaCVGQQfzlitEudJ7fhSxTKthzT3YSmc7jD3MZZw60sAsyuctRFCSlVN/fhNZyEwSKNLMaBmmz2M3cCy+I5Ok7Vq2I1Fw80rHMcDQx7+BoHTZRAK2g/eg5mIm/955SbKbUyFGRDUahxTZ0H3LWNpwCvXWXyBkHEcrgo="
    # DOCKER_PASS
    - secure: "M572Y2RYI/QIFLLbj7KyI2tsu2gYAClUfsk1DH5o0PAKVrcR7LhT4HE4aOY6PUgm+s+W3l6nowH/+puO8bErwB7Ew5qKETyBJ6by7Fdg6tDRqWkUqkLncHeQZxjsIuTsfUNgoBsAOrFAea49BSjpQItmrjd3yBTnCWpbiL6IlBKJ5THJQfb1UI5cgTmCZYYiMUsxU/JCB7LkIri1botwySKpoTsmWZOHADKOQ4VuRcQpv3T+tRrw6lngVXtLFLuNZcxArMxoEE/7XVjk/GaWi0O7OkBzF6GeEDzNwBkQSxiiPlNfYJApIkUz1iaM5e/f7JXqYLWCWv8sAJEgYCLfDDMlaSZnVd5INkXCApP28OqgwV9ljUyXxwie4oKBeHdc0IjgsOg/5xat4DqjRaDA7rlY0O81KIyUmzKJVi2KE7N9EpT4YPtrvO/ww8dmXIf7DRVhSKrnXEZoRhP7wBXRJWehfCh3MVYiJ7lffxMWOYDtFWzzxAkNBvbBD3DfC+p70JjhiTLTo9AtOtljW6CAqdXcO8rK9MZm1VUpNWRTtZhXLdDWIM4n89ZwWknmYhd0II6249pgto9JP5G55HbvyHN6zjgnGnCJnNUQzT9XR2E77612zo46JrByLXBslYebCF1birwaYBp6+c58oBOS06GPTh/kA1dOCIYvRD6re7M="
    - DOCKER_REPO=spreadspace/sfive

script:
  ### pull current images to potentially use docker build cache
  - docker pull $DOCKER_REPO:latest
  ### build the new images
  - docker build -t $DOCKER_REPO:latest .
  - docker tag $DOCKER_REPO:latest $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  ### push to docker-hub
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker push $DOCKER_REPO:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_REPO:latest
